schema_version: 1

context:
  name: unidep
  version: 1.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/unidep-${{ version }}.tar.gz
  sha256: 73ac0292da941a23af63fb80942ac404ae62b6c9de8807d7a8777343f5723f49

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - unidep = unidep:_cli.main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - ruamel.yaml
    - typing-extensions
    - packaging
    - tomli

tests:
  - python:
      imports:
        - unidep
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - unidep --help

about:
  summary: Unified Conda and Pip requirements management.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/basnijholt/unidep/

extra:
  recipe-maintainers:
    - basnijholt
